"""initial migration with users, claims, and audit_results tables

Revision ID: 69146fa7
Revises:
Create Date: 2025-11-12 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69146fa7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('claim_id', sa.String(length=255), nullable=False),
    sa.Column('member_id', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('date_of_service', sa.Date(), nullable=False),
    sa.Column('cpt_code', sa.String(length=50), nullable=False),
    sa.Column('charge_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_id'), 'claims', ['claim_id'], unique=True)
    op.create_index(op.f('ix_claims_cpt_code'), 'claims', ['cpt_code'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_member_id'), 'claims', ['member_id'], unique=False)
    op.create_index(op.f('ix_claims_provider_id'), 'claims', ['provider_id'], unique=False)
    op.create_table('audit_results',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('claim_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('issues_found', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suspicion_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recommended_action', sa.String(length=500), nullable=False),
    sa.Column('audit_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_results_claim_id'), 'audit_results', ['claim_id'], unique=False)
    op.create_index(op.f('ix_audit_results_id'), 'audit_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_results_id'), table_name='audit_results')
    op.drop_index(op.f('ix_audit_results_claim_id'), table_name='audit_results')
    op.drop_table('audit_results')
    op.drop_index(op.f('ix_claims_provider_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_member_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_cpt_code'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
